### PR TITLE
Inline editing bugfix

### LINKED ISSUE #295: Fix duplicate text of Service status
If PO or superuser edits the service status and saves the change, the text for status gets duplicated, e.g. developmentdevelopment.

# Definition of done
- [ ] When saving updated service status, status text appears only once in service header.

### LINKED ISSUE #337: Inline editing text keeps doubling
We have had struggles with the reactive inline editing of text. Check all templates with inline editing capabilities to ensure the text is not duplicated on screen when saving.

Specifically:

- [x] Organization page
- [x] Department page
- [x] Service page

### PR DESCRIPTION
**Pull request by jykae**
Closes #337
Closes #295 

# Proposed changes
- keep track when service status is updated, remove duplicate on instance.autorun
- remove unsaved style when saved

@Digipalvelutehdas/dipor-team please review.

### CODE REVIEW

**Comment by jykae** [comment]
@brylie Did it work for you or not?

**Comment by jykae** [comment]
@brylie I create separate branch/PR for trying X-editable: https://vitalets.github.io/x-editable/

**Comment by brylie** [comment]
OK, cool. Should we merge this branch?

**Comment by jykae** [comment]
Not yet, if that X-editable works better overall, let's go with that.

**Comment by frenchbread** [comment]
Good job! Thanks for fixing this 👍

**Comment by brylie** [comment]
Closing this PR for now. We can re-open, if x-editable does not work.

**Pull request closed without merging**
