### PR TITLE
Feature/authentication GitHub integration settings form

### LINKED ISSUE #259: Enable authentication for Github integration when saving settings form
When editing the settings form and changing the Github authentication settings, make sure our platform authenticates with Github. 

# Definition of done
* [ ] The settings UI contains the Github authentication fields used by the [githubAuthenticate()](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/integrations/github/server/github.js#L11) server method
* [ ] When saving a Github authentication settings through the settings UI, our system authenticates with Github
* [ ] After authenticating with Github, all Github API calls are authenticated

# Resources
See the following server-side method in our project source:
- [githubAuthenticate()](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/integrations/github/server/github.js#L11)

### PR DESCRIPTION
**Pull request by elnzv**
Closes #259

### CODE REVIEW

**Comment by brylie** [comment]
@elnzv what is the status of this PR?

**Comment by brylie** [comment]
@jykae will you please review this PR when it is ready?

**Comment by elnzv** [comment]
@Digipalvelutehdas/dipor-team, please review.

**Comment by brylie** [comment]
@jykae what is the status of this PR review?

**Comment by jykae** [comment]
@elnzv @brylie Reviewing now..

**Comment by jykae** [comment]
@elnzv What sort of permissions you decided for personal token? Should we have some sort of recommendation of that?

**Comment by elnzv** [comment]
None actually. Those mostly for private repos and when you want to grand
somebody do something on your behalf.

On Wed, 27 Apr 2016 at 14:22 Ville Jyrkkä <notifications@github.com> wrote:

> @elnzv <https://github.com/elnzv> What sort of permissions you decided
> for personal token? Should we have some sort of recommendation of that?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Digipalvelutehdas/dipor-dashboard/pull/262#issuecomment-215053822>
>
-- 

Illya Nizyev ~ www.nzv.nz

**Comment by jykae** [comment]
@elnzv Looked good, so small fixes that I did them, while on the branch. I would prefer absolute path in "import statement" if we are moving files around, elsewhere we have it that way I think. Also updated error log message. I'll merge this in.

**Pull request merged**
