### PR TITLE
Feature/department inline editing

### LINKED ISSUE #51: Add inline editing to single department view
Add inline editing functionality to single department view. 

Definition of done
---
* [ ] Edit button for organization view exists.
* [ ] Clicking edit button enables inline editing for page elements
* [ ] Clicking save button saves changes to database.
* [ ] Cancel button disables edit more
* [ ] Only edit button or save and cancel buttons are available at any given time.
* [ ] Edit and save / cancel buttons are available only for administrators.

### PR DESCRIPTION
**Pull request by frenchbread**
Closes #51 

# Proposed changes
- Added inline editing to single department view
- Added `updateAt` and `createdAt` auto value fields to department schema
- Changed `updateAt` and `createdAt` auto value fields in oraganization schema

@Digipalvelutehdas/dipor-team please review.

### CODE REVIEW

**Comment by frenchbread** [comment]
Waiting for #95

**Comment by frenchbread** [comment]
Ready for review. Please review & test.

**Comment by brylie** [comment]
When editing a department and saving the title, the breadcrumb does not update with the new department name. Make sure the breadcrumb is getting the department in a reactive context.

**Comment by brylie** [comment]
I have pushed a change that switches from a static instance variable to a reactive variable. That way the helper function should re-run when the organization/department are updated.

**Comment by frenchbread** [comment]
Thanks for fix.

**Comment by frenchbread** [comment]
Tested - it works!

**Pull request merged**
