### PR TITLE
Feature/departments rest api

### LINKED ISSUE #55: Create the REST API for departments collection
Create REST API endpoints for departments collection (organization departments publication, single department publication).

Definition of done
---
* [x] REST package has been added to project.
* [x] REST routes have been added for departments collection.
* [x] REST routes have access control.

### PR DESCRIPTION
**Pull request by jykae**
Closes #55 

# Proposed changes
- add REST endpoints for departments

@Digipalvelutehdas/dipor-team please review.

### CODE REVIEW

**Comment by jykae** [comment]
@Digipalvelutehdas/dipor-team ready for review. I pulled permissions from #52 @frenchbread has also check for insert in #80

**Comment by jykae** [comment]
Waiting #80 to be merged.

**Comment by jykae** [comment]
Probably switching to Restivus, check PR #88

**Comment by brylie** [comment]
Should we close this PR?

**Comment by jykae** [comment]
Closing.

**Pull request closed without merging**
