### PR TITLE
Feature/edit data source

### LINKED ISSUE #239: Allow editing of Github sources on Service view
An end-user may need to edit details about a Github source, e.g. to correct a spelling mistake. Add an 'edit' button next to each Github source, allowing an end-user to change Github details.

As an administrator or service owner I need to be able to edit Github source details so that I can correct error or change details.

# Definition of done
- [x] Edit button exists next to Github repository name.
- [x] When clicking the edit button, user is represented with an edit form.
- [x] When clicking save, 
  - [x] the data source is updated.
  - [x] the sync function(s) are run. (Edit by bajiat 2016-05-13: This is optional)
- [x] Allow deleting a repository from the services view (Edit by bajiat 2016-05-13)

### PR DESCRIPTION
**Pull request by frenchbread**
Closes #239 

# Proposed changes
### Visual
- Add modal window to edit data source
- Add modal (confirmation) window to remove data source
- Add edit source button
- Add remove source button

### Development
- Add `singleSource` publication
- Add autoform hook to sync github data after editing
- Fix stargazers sync
- Add permissions to update & remove to `Sources` collection

@Digipalvelutehdas/dipor-team Please review.

### CODE REVIEW

**Comment by frenchbread** [comment]
Date source is successfully updated when the edit form is submitted. 

Code for syncing is also written.

Since we are using `onSuccess` [autoform hook](https://github.com/aldeed/meteor-autoform#callbackshooks), when it's called it does return only the amount of records updated - but not any reference to updated data source. (neither ID nor user/repo). So syncing methods are not called.

We could rather use `onSubmit` hook so that the actual data source document is returned into a callback. That way we'll be able to sync related github data. `onSubmit` has also an issue that it's not finished until all its methods executed but we could bypass that by "closing" the call before and "move" sync methods to be executed in the background so that editSource-modal is closed instantly.

**Comment by frenchbread** [comment]
Please review & test 😃

**Comment by jykae** [comment]
Reviewing

**Comment by jykae** [comment]
Everything working good, though I had to look a while where the "Edit" & "Remove" button. 
Was intuitively looking them from right side as Add Source button is also there.

Just visual/usability improvements:
Maybe they could be in their own column where the sync button is? 
And they could be buttons like "Sync".

We discussed this in the office and @brylie promised to do visual changes.

**Comment by frenchbread** [comment]
@jykae As we discussed on Friday to keep edit/remove buttons in the left column, I decided to go with it. I think that moving it to separate column will take some space that is better to be used by charts. But as referring to #361 (Remove sync button) probably it's okay. Anyway feel free to make changes.

**Comment by jykae** [comment]
Ok, I filed this as enhancement https://github.com/Digipalvelutehdas/dipor-dashboard/issues/368 and merging this.

**Pull request merged**
