### PR TITLE
Feature/service view inline editing

### LINKED ISSUE #107: Add inline editing to single service view
Add inline editing functionality to single service view. 

Definition of done
---
* [x] Edit button for single service view exists.
* [x] Clicking edit button enables inline editing for page elements
* [x] Clicking save button saves changes to database.
* [x] Cancel button disables edit more
* [x] Only edit button or save and cancel buttons are available at any given time.
* [x] Edit and save / cancel buttons are available only for administrators.

### PR DESCRIPTION
**Pull request by frenchbread**
Closes #107 

# Proposed changes
- Added Inline-editing feature to single service view
 - Medium Editor
 - UI Buttons (Edit, Update, Cancel)
 - Changed Services document fetch approach -> Wrapped into autorun function
- Added permissions (Insert, Update) for Service collection
- Added `currentUserIsOwner` collection helper to Service collection
- i18n tags for buttons text

@Digipalvelutehdas/dipor-team please review.

### CODE REVIEW

**Comment by brylie** [comment]
One enhance we need, which can be made as part of a separate task:

* Use select menu for service stage field

In effect, the service stage allows only specific values, such as "idea", "planning", etc.

**Comment by brylie** [comment]
I opened issue #154, so that we can merge this task without a project status select menu.

**Comment by frenchbread** [comment]
@brylie Yup. I agree. I wanted to solve the select box thing in this PR, but could not find ready solution and decided not to hardcode it for now.

**Comment by brylie** [comment]
OK, should we disable inline edit for that field, in this PR?

**Comment by frenchbread** [comment]
Good point! I disabled it

**Pull request merged**
