### PR TITLE
Landing page organizations catalog

### LINKED ISSUE #289: Include organization catalog to landing page
All organizations catalog can be viewed in the landing page. Include counts of services by status for each organization.

# Wireframe(s)
wireframe.png)

# Definition of done
- [ ] All organization catalog views is included in landing page.

### PR DESCRIPTION
**Pull request by elnzv**
Closes #289 

Proposed changes:
- moved all organizations header to own template
- moved all organizations list to own template
- added all organizations block to landing
- added about block to landing
- moved all organizations link

screencapture-localhost-3000-1462341254165

### CODE REVIEW

**Comment by brylie** [comment]
@elnzv what is the status of this PR?

**Comment by elnzv** [comment]
It's about to be ready for the review. Adding texts suggested by @nazarah.

On Tue, 3 May 2016, 12:16 Brylie Christopher Oxley, <
notifications@github.com> wrote:

> @elnzv <https://github.com/elnzv> what is the status of this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Digipalvelutehdas/dipor-dashboard/pull/306#issuecomment-216475580>
>
-- 

Illya Nizyev ~ www.nzv.nz

**Comment by elnzv** [comment]
@Digipalvelutehdas/dipor-team, please review.

**Comment by brylie** [comment]
Looking good. I will review today.

**Pull request merged**
