### PR TITLE
Ensure unique Github issue ID

### LINKED ISSUE #226: Ensure the `id` field is unique for Github issue data
Each Github issue seems to have a unique `id` field. Ensure that our collection enforces uniqueness for the `id` field, to prevent duplicate data.

# Definition of done
- [ ] `id` field in [`GithubIssues` collection](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/integrations/github/issues/collection/collection.js#L1) has rule to ensure uniqueness

# References
- Github issues [collection index](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/integrations/github/issues/collection/collection.js#L5-L10)
- Github commits [collection index with ensure unique](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/integrations/github/commits/collection/collection.js#L7)
- EnsureIndex {Mongo docs}(https://docs.mongodb.org/v2.6/reference/method/db.collection.ensureIndex/)

### PR DESCRIPTION
**Pull request by jykae**
Closes #226 

# Proposed changes
- ensure unique Github issue ID

@Digipalvelutehdas/dipor-team please review.

### CODE REVIEW

**Comment by brylie** [comment]
@frenchbread just a clarification, are issue `id`s unique on Github, or is it possible that two repositories can have the same issue `id` returned in our API query?

**Comment by jykae** [comment]
Hmm, might be logical error.. So we are pushing ALL our Github issue data to that collection?
@brylie Wouldn't it suffice that we have automatically generated collection "_id" for each collection? That is unique, and (I suppose) by default indexed.

**Comment by brylie** [comment]
@jykae yes, the `_id` field is for our GithubIssues collection unique key. 

The question here is:
* how do we uniquely identify issues returned by the Github API?

**Comment by brylie** [comment]
@Alapan please be aware that @jykae is working with the GithubIssues `id` field. We need to know whether the `id` is unique for each Github issue, or whether different Github issues can have the same `id`.

**Note**: The Github `id` field is distinct from our GithubIssues internal `_id`, so please avoid confusing the two.

**Comment by brylie** [comment]
@jykae we are planning to use the Github unique key in order to synchronize issues from Github, via a cron task:

https://github.com/Digipalvelutehdas/dipor-dashboard/blob/feature/scheduling-function-fixes/integrations/github/issues/server/methods.js#L115

**Comment by brylie** [comment]
This code looks good, and I would like to merge it ASAP. :smiley:

**Comment by brylie** [comment]
Merged, as it seems like Github ID field is unique for each issue. 

Here are two example issues from the Github API:

```js
[
  {
    ...
    "id": 149725941,
    "number": 250,
    "title": "User/Repository names given in upper case letters returns no data for the contributors",
    ...
  },
  {
    "id": 149709022,
    "number": 249,
    "title": "Notify users while adding duplicate repositories",
  }
]
```

**Comment by Alapan** [comment]
@brylie Is it unique for issues from different repos?

**Comment by brylie** [comment]
@Alapan, what are your thoughts?

**Comment by jykae** [comment]
Oh, "number" is different than "id" then this might just work :)

**Pull request merged**
