### PR TITLE
Feature/remove organizaton and department members

### LINKED ISSUE #285: Remove organization and department members
As a superuser, organization administrator or department administrator, I want to add and remove department members.

# Definition of done
## Department members
- [ ] Superuser can add and remove department members globally.
- [ ] Organization administrators can add and remove department members only inside their organization.
- [ ] Department administrators can add and remove department members only inside their department.

## Organization members
- [ ] Superuser can add and remove organization members globally.
- [ ] Organization administrators can add and remove organization members only inside their organization.

### PR DESCRIPTION
**Pull request by frenchbread**
Closes #285 

### TODO:

- [x] Add permissions check ( happening in PR #330 )

##### Current (Remove organisation members feature):
- [x] Add i18n tags
- [x] Add comments

##### Remove department members feature:
- [x] Use same feature for department members

### CODE REVIEW

**Comment by jykae** [comment]
@frenchbread I added closes and pointer for permissions to my PR.

**Comment by frenchbread** [comment]
@jykae 👍

**Comment by bajiat** [comment]
@frenchbread Is the status of this PR same as the list above?

**Comment by bajiat** [comment]
@frenchbread Could you give us the status of this PR?

**Comment by frenchbread** [comment]
The status is as in the description. I am going to finish it later today.

**Comment by bajiat** [comment]
@frenchbread Any update on this PR?

**Comment by frenchbread** [comment]
Working on it

**Comment by brylie** [comment]
@frenchbread we are both working on a similar issue. Can we work together here?

**Comment by frenchbread** [comment]
@brylie Sure. I almost finished this one. I'll just make sure that the code is fine and remove `WIP`

**Comment by brylie** [comment]
OK, cool. Also be sure to resolve the conflicts.

**Comment by frenchbread** [comment]
Please review.

**Comment by brylie** [comment]
@frenchbread I made some significant changes to this branch, and am still working a bit. I will update you when my changes are finished.

**Comment by brylie** [comment]
I am noticing that removing an admin user from an organization does not remove the user ID from the `organization.administratorIds` array. Currently working on this issue.

**Comment by brylie** [comment]
The user interfaces should all be consistent. The last few commits have updated the confirmation modals, so they have consistent layout, color, wording, etc.

**Comment by brylie** [comment]
Behind the scenes, we are still doing things inconsistently. In the remove organization modal, we call the MongoDB update method directly from the client. However, in other remove member modal(s) we are relying on server methods. Lets use the client method for all modals, and delete the server methods.

**Comment by brylie** [comment]
We should also show the success  or failure message for all of the delete modals.

**Comment by brylie** [comment]
I have updated all remove dialogues to call the database update from client code, and removed unnecessary server methods.

The last part is to show success or failure modals.

**Comment by frenchbread** [comment]
Ok cool. Also should we allow to admin to remove himself from the organizaiton/service. In that case noone will be able to manage managers..

**Comment by brylie** [comment]
Test with the current branch. That should be fixed already.

**Comment by brylie** [comment]
Also, do you think we can remove the sAlert messages, or should we make sAlert messages for all of the pages? In any case, we should be consistent.

**Comment by brylie** [comment]
Would you please finish the task by either
- using sAlert in all of the remove member/owner/admin dialogues
- removing sAlert from the 'remove organization member' dialogue

**Comment by brylie** [comment]
@bajiat suggests that is OK to remove the sAlert dialogue from the organization delete modal.

**Comment by brylie** [comment]
I will check back with you tomorrow, to see if we can merge this code then.

**Comment by frenchbread** [comment]
Cleaned up & removed sAlert.

**Comment by bajiat** [comment]
@frenchbread Is this ready to be merged? Can we clear the WIP label?

**Comment by frenchbread** [comment]
Removed `WIP`. Please review/merge.

**Pull request merged**
