### PR TITLE
Feature/organization schema

### LINKED ISSUE #9: Create organization collection and schema
_From @bajiat on February 19, 2016 12:14_

Based on user requirement document, create organize collection and define organization schema with at least most relevant fields.

Definition of done
---
* [ ] Organization collection exists.
* [ ] List of organization collection fields exists in plain text in this issue.
* [ ] Schema exists for most relevant fields.
* [ ] Schema has been attached to collection.

# Fields
These will be the initial fields for the Organizations collection schema:
## `name` 
* type: String
* regExp: Unique ID

## `admin`
Depending on whether we anticipate supporting multiple administrators per organization, we will create one of the following:

* administratorId - single administrator ID
* administratorIds - array of one or more administrator IDs

# Related
See the requirement document for [details about this feature](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/master/docs/requirements.md#organization-view-registered-user-who-is-a-member-of-the-organization-in-question).

## Dependent issues
* #17
* #18
* #19 

_Copied from original issue: Dipor/platform#8_

### PR DESCRIPTION
**Pull request by brylie**
Closes #9 

# Proposed changes
- Add Organizations collection
- Add initial schema for Organizations collection

@Digipalvelutehdas/dipor-team please wait to merge this until we have clarification about the "administrator(s)" field.

### CODE REVIEW

**Comment by bajiat** [comment]
@brylie should we merge this or not? or should we review the open issues first?

**Comment by frenchbread** [comment]
I think let's merge this & then, if needed, we can easily change `administratorId` field to be an array.

**Comment by brylie** [comment]
@frenchbread if we later decide to change the `administratorId` field to be an array, we would at least need to make some additional modifications:

* provide a migration for the schema change
* update any collection helpers related to fetching administrator documents (from the user collection)
* update any authentication logic in collection allow/deny rules
* update any template authentication logic in heloers, etc

While none of these aspects currently exist, we will add them shortly after completing this task.

**Comment by bajiat** [comment]
Labeled as WIP because AdministratorId to be changed to an array based on comment from @kyyberi.

**Comment by brylie** [comment]
@elnzv I have updated the schema to allow multiple administrators per organization.

**Comment by brylie** [comment]
I also added contact person and description fields.

**Comment by brylie** [comment]
@frenchbread go ahead and pull these changes into your working branch.

**Comment by frenchbread** [comment]
@brylie Thanks!

**Comment by bajiat** [comment]
@elnzv Based on review of the data model diagram, there are a few updates that are needed. Hence, PR is labeled as WIP for the time being.

**Comment by frenchbread** [comment]
What about adding "Organization avatar picture" field? I am currently building a markup for organization view and want to clarify this. 

Also field like "home page URL" can be added to make the view contain more info about organization.

Otherwise I can make simplified version of the layout for now, until wireframes are created.

**Comment by brylie** [comment]
@frenchbread the 'avatar'/'logo' field may not be a requirement. Also, we are not sure right now whether 'home page URL' is a requirement. Lets start with what [we are sure of](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/develop/docs/requirements.md#organization-view-registered-user-who-is-a-member-of-the-organization-in-question), and improve later.

**Comment by brylie** [comment]
@elnzv FWIW, PR #9 is waiting for this to be merged.

**Pull request closed without merging**
