### PR TITLE
Feature/292 superuser permissions

### LINKED ISSUE #292: Enhance insert and update permissions
Check the insert and update permissions for departments and services. Specifically, ensure that a superuser can add and update anything. Ensure that only superusers, organization and department administrators can add services.

As a superuser, I need to be able to edit any information in the system so that I can support organization/department administrators and other users.

# Definition of done
User with 'admin' can
- [x] add organizations, departments and services.
  - [x] add departments for organizations when they are not in the `administratorIds` array
  - [x]  add services for departments when they are not in the `administratorIds` array
- [x] add members.
  - [x] add members for organizations when they are not in the `administratorIds` array
  - [x] add members for departments when they are not in the `administratorIds` array
- [x] add organization/department administrators.
 - [x] add administrators for organizations when they are not in the `administratorIds` array
  - [x] add administrators for departments when they are not in the `administratorIds` array
  - [x] add owners for services when they are not in the `ownerIds` array
- [x] edit organization,  department and service information.
  - [x] edit organizations when they are not in the `administratorIds` array
  - [x] edit departments when they are not in the `administratorIds` array
  - [x] edit services when they are not in the `ownerIds` array

Co-pilot: @brylie

### PR DESCRIPTION
**Pull request by jykae**
Closes #292 

# Proposed changes
- add currentUserCanManageOrganization helper & checks
- add currentUserCanManageDepartment helper & checks
- add currentUserCanManageService helper & checks
- managing admins for organization & department
- enhance allow/deny rules for collections (insert/update)

@Digipalvelutehdas/dipor-team please review.

### CODE REVIEW

**Comment by jykae** [comment]
@Digipalvelutehdas/dipor-team please review

**Comment by elnzv** [comment]
screencapture-localhost-3000-service-mkbjswjmqhfmnuzfs-1462869938161

Check for permissions here.
Hide delete button for not admin. And disable delete button for current user in general.

**Comment by jykae** [comment]
@elnzv changes made. Improved also insert permissions after discussion with @brylie

**Comment by elnzv** [comment]
Looks good. There are couple things we need to fix, because of structure change. Rising issues for those.

**Pull request merged**
