### PR TITLE
Hotfix/remove data source

### LINKED ISSUE #369: 'Delete/Remove' Github data source in service view fails
# 'Delete/Remove' Github data source in service view fails
    User unable to remove/delete github source in service view

# Steps to reproduce  

1. Visit https://dashboard.digipalvelutehdas.fi

2. Login

3. Create Organization

4. Go to Organization view and select the organization added above

5. Create Department

6. Go to department view

7. Add 'Service'  

8. Go to department view and select the service added above       

9. Click on 'Add Source'    

10. Go to source and delete source added above  
  
# Observed behavior
   Delete github data source in service view fails

# Expected behavior  
   User must be able to delete github data source in service view  

- Web browser: 
  -  Mozilla Firefox 44.0
  -  Chrome 48.0.2564.103

- Operating system  
  - Linux : Ubuntu 14.04.03 LTS (Trusty)

### PR DESCRIPTION
**Pull request by frenchbread**
Closes #369 

# Changes
- Add method to remove data source

@Digipalvelutehdas/dipor-team please review

### CODE REVIEW

**Comment by brylie** [comment]
Is this hotfix fixing a bug? It may be OK to call the .remove method directly in the client, since our authentication check happens at the database level.

**Comment by frenchbread** [comment]
@brylie Actually I did not expect if to fix the issue but it did. Don't see any other errors or typos that can resolve it.

**Comment by frenchbread** [comment]
Currently there is a direct `.remove` call, which for some reason gives an error. On my machine this PR resolves it

**Comment by brylie** [comment]
Alright. What is the error by the way?

**Comment by frenchbread** [comment]
```
Exception while invoking method '/sources/remove' ReferenceError: source is not defined
```

**Comment by brylie** [comment]
OK, on what line are you defining `source`?

**Comment by brylie** [comment]
Anyway, we can merge this. It just seems like it should work in the client code.

**Comment by frenchbread** [comment]
Here is the full trace:
```
I20160516-13:09:30.760(3)? Exception while invoking method '/sources/remove' ReferenceError: source is not defined
I20160516-13:09:30.760(3)?     at remove (/Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/app/app.js:3080:23)
I20160516-13:09:30.760(3)?     at /Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/allow-deny.js:382:13
I20160516-13:09:30.761(3)?     at /Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/underscore.js:255:41
I20160516-13:09:30.761(3)?     at _.each._.forEach (/Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/underscore.js:142:22)
I20160516-13:09:30.762(3)?     at Function._.every._.all (/Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/underscore.js:254:5)
I20160516-13:09:30.763(3)?     at [object Object].CollectionPrototype._validatedRemove (/Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/allow-deny.js:381:9)
I20160516-13:09:30.763(3)?     at [object Object].m.(anonymous function) (/Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/allow-deny.js:185:48)
I20160516-13:09:30.764(3)?     at maybeAuditArgumentChecks (/Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:2106:12)
I20160516-13:09:30.765(3)?     at /Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:1047:22
I20160516-13:09:30.767(3)?     at [object Object]._.extend.withValue (/Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/meteor.js:1107:17)
I20160516-13:09:30.768(3)?     at /Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:1046:43
I20160516-13:09:30.768(3)?     at [object Object]._.extend.withValue (/Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/meteor.js:1107:17)
I20160516-13:09:30.769(3)?     at /Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:1045:48
I20160516-13:09:30.770(3)?     at tryCallTwo (/Users/damir/.meteor/packages/promise/.0.6.7.dq0a4p++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20160516-13:09:30.771(3)?     at doResolve (/Users/damir/.meteor/packages/promise/.0.6.7.dq0a4p++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:200:13)
I20160516-13:09:30.772(3)?     at new Promise (/Users/damir/.meteor/packages/promise/.0.6.7.dq0a4p++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:66:3)
I20160516-13:09:30.773(3)?     at Session.method (/Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:1023:23)
I20160516-13:09:30.774(3)?     at /Users/damir/Projects/samposoftware/dipor/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:885:89
```

**Pull request merged**
