### PR TITLE
Feature/case insensitive username and repository

### LINKED ISSUE #225: Determine how to handle uppercase letters in user and repository names
Github usernames are case-insensetive. However, when returning data, the username or repository seems to retain the case. In Dipor, users can enter the username and repository in any case, so the strings may not match. Determine how to handle uppercase letters in Github usernames and repositories.

### PR DESCRIPTION
**Pull request by brylie**
Closes #225

# Proposed changes
(List any significant changes or additions here)
- Use case insensitive regexp search for Github Issues
- Remove toLowerCase() calls on username and repository strings

@Digipalvelutehdas/dipor-team please review.

### CODE REVIEW

**Comment by frenchbread** [comment]
Actually we could keep `toLowercase()` to display repo names consistently since using regex. What do you think @brylie  ?

**Comment by brylie** [comment]
@frenchbread that is fine. I will commit the changes shortly.

**Comment by brylie** [comment]
Do you think we should convert the username/repository to lowercase when adding a new source from the UI?

**Comment by frenchbread** [comment]
Yes, I think so. That would be consistent.

**Comment by frenchbread** [comment]
This way we won't need to convert to lowercase when calling githubGet.. and guthubSync.. methods.

**Comment by brylie** [comment]
This turns out to be somewhat difficult. I am trying to add regex validation on the form field, and the Github username regex seems to be non-trivial:

> Github login may only contain:
         alphanumeric characters (we are enforcing lowercase for consistency)
         or single hyphens,
         and cannot begin or end with a hyphen

**Comment by brylie** [comment]
I have tried several regular expressions, and this is the latest:

`/^[a-z0-9]*(?!^)\-(?!$)*[a-z0-9]*$/`

**Comment by brylie** [comment]
@frenchbread I have managed to figure out the regular expression validation. Please review.

**Comment by frenchbread** [comment]
Tested, looks good 👍 

Merging..

**Pull request merged**
