### PR TITLE
initial structure of enhancements

### LINKED ISSUE #208: Enhance organization views
This task covers both all organizations view and single organization view. Check the wireframe for organization views and add missing fields and permissions.

@Nazarah will co-pilot

### PR DESCRIPTION
**Pull request by elnzv**
Closes #208

### CODE REVIEW

**Comment by brylie** [comment]
@elnzv what is the status of this PR?

**Comment by elnzv** [comment]
@Digipalvelutehdas/dipor-team, please review.

**Comment by jykae** [comment]
@elnzv Reviewing

**Comment by jykae** [comment]
Good improvements. Merging.

**Comment by brylie** [comment]
@jykae please also delete the branch after merging.

**Pull request merged**
