### PR TITLE
Feature/service visibility toggle

### LINKED ISSUE #192: Add UI widget for toggling Service visibility
When creating or viewing a service, a Product Owner might need to toggle the service visibility. E.g. public/private. Design and add a UI element to toggle the service visibility, at least in two places:

- Add Service form
- View Service page

Also, perform a check on the route to check whether user is authorized to view the service or not. If not authorized, show 403 template.

Blocks #297.

# Definition of done
- [ ] Add service form contains a visibility widget (a field or similar) for setting the service visibility as public or private.
- [ ] View Service page also contains visibility widget for setting the service visibility as public or private.
- [ ] Toggling the visibility widget updates the service visibility field.
- [ ] Route permission check exists for direct service route.
  - [ ] Route permission checks whether the service is public. If service is private, it checks the user permission. If the user is not authorized to view the service, 403 is displayed.

### PR DESCRIPTION
**Pull request by brylie**
Closes #192

# Proposed changes
- Added service visibility toggle to "Single Service" header template
- Dynamically toggle visibility switch when page renders
- Update service visibility when toggling widget
- Widget only visible for "Service Owner"

# Todo
- Use @jykae's `currentUserCanManageService` collection helper to toggle visibility of "Visibility" widget.
- Consider refactoring the `visibility` field to be more semantic (e.g. `service.isPublic: true`, or `service.public: true`
  - `public`: Boolean

@Digipalvelutehdas/dipor-team please review.

### CODE REVIEW

**Comment by brylie** [comment]
@bajiat, this is ready for review.

**Comment by jykae** [comment]
@brylie helpers shortened, feel free to pull again

**Comment by brylie** [comment]
This is basically working. I tried to place the toggle on each service in the department page, but it didn't work properly. There were also layout difficulties.

**Comment by jykae** [comment]
Reviewing

**Comment by jykae** [comment]
Marked down that schema field changes, so I remember to check that on deploying.
Worked good. Merging.

**Pull request merged**
